// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PermissionSystem.Infrastructure.Data;

#nullable disable

namespace PermissionSystem.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611090000_AddDemoBusinessOrder")]
    partial class AddDemoBusinessOrder
    {
    }
}
